Fix/select
naveteam/nave-kit pull request #142
Opened 2020-10-26 20:47 UTC by italonolasco

## Descreva o que foi feito neste PR (Obrigatório)
Fix do Select. Troca para id e sempre mostrar label

2020-10-26 22:33 UTC, devSiso approved these changes, later dismissed

2020-10-26 22:33 UTC, devSiso commented on src/components/Select/Select.jsx
> +                  <option key={option.id} value={option.id}>
acho que podemos manter aquela lógica de passar o valor da chave, optionLabel/optionValue. assim fica menos chumbado

2020-10-26 22:40 UTC, gcdpinho requested changes

2020-10-26 22:40 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +    const [optionSelected, setOptionSelected] = useState([])
armazena um objeto

2020-10-26 22:40 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +                    {optionSelected[1] || placeholder}
armazena o objeto e usa OptionSelected.label

2020-10-28 14:05 UTC, gcdpinho approved these changes

2020-10-28 14:05 UTC, merged