fix(select): remove unecessary onchangeHandler and value
naveteam/nave-kit pull request #148
Opened 2020-10-30 18:45 UTC by italonolasco

## Descreva o que foi feito neste PR (Obrigatório)
Remove onChangeHendler e value desnecessário

2020-10-30 19:02 UTC, gcdpinho requested changes

2020-10-30 19:02 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +            <SelectBase name={name} ref={ref} isDirty={!!optionSelected.value}>
usa `optionSelected[optionValue]`. A ideia é que essa key (value) também possa ser parametrizavel

2020-10-30 19:02 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +              <option selected disabled value={false}>
Pq mudar para false?

2020-10-30 19:02 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +                  selected={optionSelected.value === option[optionValue] ? true : false}
esse selected é realmente necessário?

2020-10-30 19:10 UTC, devSiso commented on src/components/Select/Select.jsx
> +                  selected={optionSelected.value === option[optionValue] ? true : false}
Sim, é através dele que o componente renderiza a option selecionada dentro do campo, sem ele, precisariamos passar um value para o Select, o que dá conflito no nosso RHF

2020-11-03 17:38 UTC, gcdpinho approved these changes

2020-11-03 17:38 UTC, merged