feat(accordion-detail-padding): add custom detail padding
naveteam/nave-kit pull request #149
Opened 2020-11-03 16:51 UTC by thiagonunesbatista

O que foi feito?
Surgiu uma demanda interna de ter um padding diferente do padding padrão no conteúdo dentro de um accordion, para solucionar isto foi adicionado uma nova prop ao Accordion Detail que permitirá isso

2020-11-03 16:58 UTC, UsefulHunter approved these changes, later dismissed

2020-11-04 11:23 UTC, devSiso requested changes

2020-11-04 11:23 UTC, devSiso commented on src/components/Accordion/Accordion.jsx
> +  ({ detailPadding, expanded, detailColor }) => css`
Dar preferência ao styled system ao invés de utilizar props de espaçamento.

2020-11-04 11:59 UTC, gcdpinho commented on src/components/Accordion/Accordion.jsx
> +  ({ detailPadding, expanded, detailColor }) => css`
eu concordo com o @devSiso. Se tu passar um spread de props para o AccordionContent e importar space (e talvez até o layout) do styled funciona bem.

2020-11-04 17:22 UTC, gcdpinho approved these changes

2020-11-04 17:26 UTC, devSiso approved these changes

2020-11-04 17:26 UTC, merged