feat(clear-select): add function
naveteam/nave-kit pull request #169
Opened 2020-11-26 16:28 UTC by thiagonunesbatista

O que foi feito?
Adiciona a funcionalidade de limpar o select. Basta passar uma prop e a função estará ativa. Para mais detalhes acesse o video que gravei explicando a implementação:

https://youtu.be/x2ONQUIVYaw

2020-11-27 12:54 UTC, gcdpinho requested changes

2020-11-27 12:54 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +              {clearValue && Object.keys(optionSelected).length > 0 && (
Acho que seria melhor testar o direto `optionSelected[optionValue]`. Como é um teste de render, qualquer diferença de performance é interessante. Assim, tu não vai ter uma operação de transformar um obj e em array.

2020-11-27 12:54 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +      clearValue,
Acho que esse cara podia ter defaultValue true. Pensando que a ideia é que todos os selects tenha a opção de limpar o valor. O que tu acha?

2020-11-27 12:54 UTC, gcdpinho commented on src/components/Select/Select.jsx
> +      e.stopPropagation()
Outra coisa que seria legal era passar um função custom de clear. Semelhante ao comportamento `onOptionSelected`, mas para eu conseguir realizar o trigger em uma função externa ao limpar.

2020-12-01 14:20 UTC, gcdpinho approved these changes

2020-12-02 11:58 UTC, italonolasco approved these changes

2020-12-02 12:00 UTC, merged