refactor: change loader prop's "variant" prop to "type"
naveteam/nave-kit pull request #183
Opened 2021-02-05 16:19 UTC by dpnunez

Trocar nome da prop `variant` para `type`

2021-02-05 19:47 UTC, rbschumacher requested changes

2021-02-05 19:47 UTC, rbschumacher commented on src/stories/Loader.stories.mdx
> +      <Loader percentage={30} showPercentage type='determinate' />
Tem q mudar na doc que recebe o type e não a variant

2021-02-05 19:47 UTC, rbschumacher commented on src/components/Loader/Loader.jsx
> +export const Loader = ({ percentage, showPercentage, size, time, type, ...props }) => {
O componente não deve continuar suportando a prop como `variant` também? Ai vai ter que continuar desestruturando ela aqui e abaixo utilizar o type ou a variant

2021-02-08 12:10 UTC, dpnunez commented on src/components/Loader/Loader.jsx
> +export const Loader = ({ percentage, showPercentage, size, time, type, ...props }) => {
boa, tinha esquecido

2021-02-08 12:11 UTC, dpnunez commented on src/stories/Loader.stories.mdx
> +      <Loader percentage={30} showPercentage type='determinate' />
o Storybook pega as props pelo proptypes

2021-02-08 12:55 UTC, rbschumacher submitted a review, later dismissed

2021-02-08 19:22 UTC, eduardobittencourt commented on src/components/Loader/Loader.jsx
>    variant: PropTypes.oneOf(['determinate', 'indeterminate'])
remover essa prop dos proptypes para evitar que novos devs usem essa prop depreciada

2021-02-10 11:51 UTC, dpnunez commented on src/components/Loader/Loader.jsx
>    variant: PropTypes.oneOf(['determinate', 'indeterminate'])
feito @eduardobittencourt!

2021-02-10 11:55 UTC, eduardobittencourt commented on src/stories/Loader.stories.mdx
> +      <Loader percentage={30} showPercentage type='determinate' />
acho que o que o shuma quis dizer aqui era ali no MD mesmo, linha 54 por exemplo

2021-02-10 12:30 UTC, eduardobittencourt approved these changes

2021-02-10 12:36 UTC, rbschumacher approved these changes

2021-02-10 12:40 UTC, merged