style: add size variants on icon
naveteam/nave-kit pull request #187
Opened 2021-02-09 14:23 UTC by dpnunez

2021-02-09 15:45 UTC, CaaioSB requested changes

2021-02-09 15:45 UTC, CaaioSB commented on src/stories/Iconography.stories.mdx
> +export const IconBase = args => console.log(args) || (
o console.log(args) é realmente necessário?

2021-02-09 15:45 UTC, CaaioSB commented on src/stories/Iconography.stories.mdx
> +    <Icon {...args} size='md' />
a prop padrão do size já é `md`, talvez não seja necessário passar o `size='md'`, ou é?

2021-02-09 16:26 UTC, dpnunez commented on src/stories/Iconography.stories.mdx
> +    <Icon {...args} size='md' />
Realmente não é necessário, mas acho válido pra deixar explicito no code snippet

2021-02-09 16:26 UTC, dpnunez commented on src/stories/Iconography.stories.mdx
> +export const IconBase = args => console.log(args) || (
Vou tirar ✂️

2021-02-10 11:58 UTC, eduardobittencourt approved these changes

2021-02-10 12:39 UTC, rbschumacher approved these changes

2021-02-10 13:23 UTC, CaaioSB approved these changes

2021-02-10 13:23 UTC, merged