fix(select-documentation): finish changes
naveteam/nave-kit pull request #191
Opened 2021-02-11 18:53 UTC by thiagonunesbatista

**O que foi feito?**
Atualizada a doc

2021-02-11 19:33 UTC, rcandia approved these changes, later dismissed

2021-02-12 12:06 UTC, dpnunez commented
Opa, acho que seria nice mudar o `onOptionSelect` para o `onChange`

2021-02-12 12:07 UTC, dpnunez commented
`onClearSelect` pra `onClear` ou `onReset`, o que acha?  a ideia é ter um padrão de prop's de controles em todos os componentes de input

2021-02-12 12:12 UTC, glauberbrack submitted a review, later dismissed

2021-02-12 12:15 UTC, dpnunez requested changes
Trocar para onChange e onClear/onReset (acabei deixando descrito no comentário, my bad)

2021-02-12 13:41 UTC, thiagonunesbatista commented
@rcandia @glauberbrack 

O que acham da sugestão do @dpnunez  de mudar os nomes das props?
`onClearSelect` pra `onClear`.
`onOptionSelect` para `onChange`.

2021-02-22 12:02 UTC, rcandia approved these changes

2021-02-22 12:20 UTC, dpnunez approved these changes

2021-02-22 12:22 UTC, merged