feat: remove xstyles from checkbox
naveteam/nave-kit pull request #227
Opened 2021-06-28 21:39 UTC by Carrilhos

Removido o @xstyled e o @xstyled-components no componente de checkbox

card: https://naveteam.atlassian.net/secure/RapidBoard.jspa?rapidView=110&projectKey=DSYS&modal=detail&selectedIssue=DSYS-437

2021-06-30 14:01 UTC, dpnunez requested changes

2021-06-30 14:01 UTC, dpnunez commented on src/components/Checkbox/Checkbox.jsx
> +  @media (max-width: 600px) {
Seria ideal a media query respeitar os breakpoints dinâmicamente. Logo mais vou testar pra ver se da pra fazer isso só com o styled-components, caso não, minha estratégia seria fazer pelo styled-system "in-line" mesmo.

2021-06-30 14:01 UTC, dpnunez commented on src/components/Checkbox/Checkbox.jsx
>    color: gray.800;
todas essas prop's que usam o nome da cor diretamente só funcionavam por causa do x-styled (o styled-components não tem a "inteligência" de pegar essa cor la no theme).
Ai ficaria da seguinte forma:

de:
> color: gray.800

para:
> color: ${({ theme }) => theme.colors.gray['800']}

2021-06-30 18:38 UTC, igorcasconi commented on src/components/Checkbox/Checkbox.jsx
>    color: gray.800;
Isso mesmo, tem que fazer essa desestruturação theme pra pegar a cor necessária.

2021-06-30 18:38 UTC, igorcasconi commented on src/components/Checkbox/Checkbox.jsx
>      color: gray.900;
Aqui também é necessário pegar a cor de theme, desse modo não funciona com styled components.

2021-06-30 18:38 UTC, igorcasconi commented on src/components/Checkbox/Checkbox.jsx
> +  @media (max-width: 600px) {
Aqui poderia usar o breakpoints do theme tambem:

` @media (max-width: ${breakpoints.sm}px) {
      display: flex;
    }`

2021-07-01 12:41 UTC, devSiso approved these changes

2021-07-01 12:45 UTC, igorcasconi commented on src/components/Checkbox/Checkbox.jsx
> +  color: ${({ theme }) => theme.colors.gray['800']};
Pra não chamar todas as vezes o theme, dá pra chamar no começo do componente:
```
const LabelContainer = styled(Flex)(({ theme: { colors, breakpoints}}) => css
....
color: ${colors.gray['800']};

....
@media (max-width: ${breakpoints.sm}px) {
    display: flex;
  }

...)
```

2021-07-01 13:20 UTC, igorcasconi commented
@all-contributors please add @Carrilhos for code and bugs

2021-07-01 14:47 UTC, dpnunez requested changes
Concordo com a dica do Igor de desestruturar o theme só uma vez! Vai resumir bastante o código;
Além disso, acho que faltou mudar a sintaxe ali no componente `UncheckIcon` (linha 52)

2021-07-02 17:52 UTC, igorcasconi approved these changes

2021-07-02 20:06 UTC, dpnunez approved these changes

2021-07-02 20:06 UTC, merged