refactor: replaced @xstyled for styled-components and styled-system
naveteam/nave-kit pull request #249
Opened 2021-08-13 13:12 UTC by Tessmer

## What does this MR do?
- replace @xstyled for styled-components and styled-system;
- adds a border radius prop.

## Related cards and external links
- [here](https://naveteam.atlassian.net/secure/RapidBoard.jspa?rapidView=110&projectKey=DSYS&modal=detail&selectedIssue=DSYS-420&assignee=60a281ac5998a60068494d5b)

## Put here related images if exists

## Checklist

- [x] Fullfil What does this MR do?
- [x] [Follow vnt git guides](https://grupo-vnt.gitlab.io/guides/nave/git/)
- [x] [Squash pull request into a single commit](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit/)
- [ ] Your team's review (required)

2021-08-13 19:23 UTC, igorcasconi requested changes

2021-08-13 19:23 UTC, igorcasconi commented on src/components/Tag/Tag.jsx
>    border-radius: 1;
Dessa forma que está o border-radius não está passando valor, aqui tem que passar igual abaixo:
`border-radius: ${props.theme.space[1]}px;`

Assim ele pega direto da configuração do `Theme.js` depois da uma olhada sobre como funciona os valores do theme

2021-08-13 19:23 UTC, igorcasconi commented on src/components/Tag/Tag.jsx
> +  font-weight: 600;
Aqui pode pegar do Theme tambem, igual funcionaria pro xstyled, lá ele possui valores para fontWeights, fontSizes e lineHeights, ai como exemplo ficaria:

```
const Text = styled(Typography)(({theme: { fontWeights, lineHeights, fontSizes }) => css`
...
font-weight: ${fontWeights[1]};
font-size: ${fontSizes[1]}px;
line-height: ${lineHeights[1]};
`
```
o link da documentação explica sobre isso:
[https://styled-system.com/theme-specification](https://styled-system.com/theme-specification)

2021-08-16 17:25 UTC, igorcasconi approved these changes

2021-08-16 18:58 UTC, dpnunez approved these changes

2021-08-16 21:16 UTC, merged